############################ General Config #######################################################
ansible_connection: local

# Please provide your redhat login credentials, can be added via the following: 
# ansible-playbook playbooks/registry.yml -e 'rh_username=' -e 'rh_password='
rh_username: ''
rh_password: ''

############################ Registry Config ######################################################
#Please give the DNS name that you're using for you registry, can be the full fqdn  
registry_full_fqdn: 'registry' 

# Please choose you wanted ocp version for mirroing images
ocp_mirror_version: '4.8.11'

# Please provide your pull secret file location, make sure it contains your offline 
# registry too 
pull_secret_location: '/root/pull-secret.json'

############################ Importing and Exporting config #######################################
# Please choose here whether you'd like to export or import the given registry data 
registry_data_action: "import"

# Please choose which location data should be taken from or copied to
# The registry.tar.gz file suffix will be added automatically 
tar_location: "/root/"

############################ Catalog Mirroring Config ##############################################
selected_operators:
#   - 3scale-operator
#   - advanced-cluster-management
#   - amq-broker
#   - amq-broker-lts
#   - amq-broker-rhel8
#   - amq-online
#   - amq-streams
#   - amq7-cert-manager-operator
#   - amq7-interconnect-operator
#   - ansible-automation-platform-operator
#   - apicast-operator
#   - awx-resource-operator
#   - businessautomation-operator
#   - cincinnati-operator
#   - cluster-kube-descheduler-operator
#   - cluster-logging
#   - clusterresourceoverride
#   - codeready-workspaces
#   - compliance-operator
#   - container-security-operator
#   - costmanagement-metrics-operator
#   - datagrid
#   - devworkspace-operator
#   - eap
#   - elasticsearch-operator
#   - file-integrity-operator
#   - fuse-apicurito
#   - fuse-console
#   - fuse-online
#   - gatekeeper-operator-product
#   - integration-operator
#   - jaeger-product
#   - jws-operator
#   - kiali-ossm
#   - klusterlet-product
#   - kubernetes-nmstate-operator
#   - kubevirt-hyperconverged
#   - local-storage-operator
#   - metering-ocp
#   - mtc-operator
#   - mtv-operator
#   - nfd
#   - ocs-operator
#   - openshift-gitops-operator
#   - openshift-jenkins-operator
#   - openshift-pipelines-operator-rh
#   - performance-addon-operator
#   - poison-pill-manager
#   - ptp-operator
#   - quay-bridge-operator
#   - quay-operator
#   - red-hat-camel-k
#   - rh-service-binding-operator
#   - rhacs-operator
#   - rhmtv-operator
#   - rhpam-kogito-operator
#   - rhsso-operator
#   - sandboxed-containers-operator
#   - serverless-operator
#   - service-registry-operator
#   - service-telemetry-operator
#   - servicemeshoperator
#   - skupper-operator
#   - smart-gateway-operator
#   - sriov-network-operator
#   - submariner
#   - vertical-pod-autoscaler
#   - web-terminal
#   - windows-machine-config-operator
