################ General Config ################################3######
ansible_connection: local

registry_full_fqdn: 'ocp-test'
ocp_mirror_version: '4.8.11'
pull_secret_location: '/root/pull-secret.json'

################### RedHat Login Info ###############################
rh_username: ""
rh_password: ""

################## Saved zip container image for whitening ############################
registry_data_action: "import" # 'export' to export a zipped file, 'import' to load the zip to an existing registry 
tar_location: "/home/spaz"
