- name: Get service firewalld service facts 
  service_facts:
  tags:
  - registry
 

- name: Configure firwall https/http access
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_facts.services["firewalld.service"]["state"] == "running"
  with_items:
  - http
  - https
  notify:
  - Restart the firewalld service
  tags:
  - registry

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  tags:
  - registry

