- name: Generate CSR
  template:
    src: csr.j2
    dest: /opt/registry/certs/csr.txt

- name: Generate the registry certificate using the provided answerfile
  shell: |
     openssl req -newkey rsa:4096 -nodes -sha256 -keyout /opt/registry/certs/registry.key -x509 -days 1825 -out /opt/registry/certs/registry.crt -config /opt/registry/certs/csr.txt

- name: Create login credentaisl using htpasswd
  command: | 
     htpasswd -bBc /opt/registry/auth/htpasswd admin admin


