- name: Generate CSR
  template:
    src: csr.j2
    dest: "{{ registry_base_dir }}/certs/csr.txt"
  tags:
  - registry

- name: Generate the registry certificate using the provided answerfile
  shell: |
     openssl req -newkey rsa:4096 -nodes -sha256 -keyout {{ registry_base_dir }}/certs/registry.key -x509 -days 1825 -out {{ registry_base_dir }}/certs/registry.crt -config {{ registry_base_dir }}/certs/csr.txt
  tags:
  - registry

- name: Create login credentaisl using htpasswd
  command: | 
     htpasswd -bBc {{ registry_base_dir }}/auth/htpasswd admin admin
  tags:
  - registry



