- name: Create systemd environment file 
  template:  
    src: registry.service.j2
    dest: "/etc/systemd/system/registry.service"
  notify:
  - Restart the registry systemd service 
  tags:
  - registry

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  tags:
  - registry


