- name: Install yum prerequisites
  yum:
    name: ['httpd-tools','podman','python3-pip']
    state: present
  tags:
  - registry

- name: Create directory tree
  file:
    state: directory
    path: "{{ registry_base_dir }}/{{ item }}"
    recurse: yes
  with_items:
  - "certs"
  - "auth"
  - "data"
  tags:
  - registry

