---
# tasks file for registry

- name: Import Prerequisites Tasks
  include_tasks: install_prerequisites.yml
  tags:
  - registry

- name: Import Authentication Tasks
  include_tasks: create_authentication.yml
  tags:
  - registry

- name: Configure Firewall Access
  include_tasks: configure_firewall.yml
  tags:
  - registry

- name: Start Registry Container
  include_tasks: start_registry.yml
  tags:
  - registry

- name: Validate Registry Configuration
  include_tasks: validate_registry.yml
  tags:
  - registry

- name: Create Registry Systemd Configuration
  include_tasks: create_systemd.yml
  tags:
  - registry

- name: Mirror Needed Disconnected Openshift Images
  include_tasks: mirror_images.yml
  tags:
  - mirror

- name: Including catalog mirroring prereqs valistion 
  include_tasks: validate_catalog_prereqs.yml
  tags:
  - catalog

- name: Getting all possible packages for mirror 
  include_tasks: get_catalog_packages.yml
  tags:
  - catalog

- name: Prunning index image according to a given operator list 
  include_tasks: prune_index_image.yml
  tags:
  - catalog

- name: Mirror catalog images to offline registry 
  include_tasks: mirror_catalog_images.yml
  tags:
  - catalog

- name: Render needed catalog files (icsp and catalgSource)
  include_tasks: render_cs_and_icsp.yml 
  tags:
  - catalog

- name: Import Disconnected Images From An Existing TAR
  include_tasks: import_images.yml
  when: registry_data_action == "import"
  tags: 
  - import-tar 

- name: Export Disconnected Images TAR for Whitening
  include_tasks: export_images.yml
  when: registry_data_action == "export"
  tags:
  - export

