- name: create mirror script on the remote host 
  template: 
    src: mirror.sh.j2
    dest: "/tmp/mirror.sh" 
    mode: a+x
  delegate_to: localhost
  tags:
  - mirror

- name: Mirror wanted ocp version installation images 
  script: /tmp/mirror.sh
  tags: 
  - mirror  


