- name: Search for any existing registry 
  shell: | 
    podman ps -a  
  register: containers_exist
  tags:
  - registry

- name: Clean exsiting registry 
  shell: | 
    podman rm -f registry 
  when: containers_exist.stdout_lines | select('search', 'registry') | list | length > 0
  ignore_errors: yes
  tags:
  - registry

- name: Start registry container using Podman
  shell: |
    podman run --name registry -p {{ registry_bind_port }}:5000 \
     -v {{ registry_base_dir }}/data:/var/lib/registry:z \
     -v {{ registry_base_dir }}/auth:/auth:z \
     -e "REGISTRY_AUTH=htpasswd" \
     -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
     -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
     -v {{ registry_base_dir }}/certs:/certs:z \
     -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt \
     -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key \
     -e REGISTRY_COMPATIBILITY_SCHEMA1_ENABLED=true \
     -d docker.io/library/registry:2
  tags:
  - registry

