- name: Copy self-signed certificate to pki directory
  copy:
    src: "{{ registry_base_dir }}/certs/registry.crt"
    dest: /etc/pki/ca-trust/source/anchors/registry.crt
  tags:
  - registry

- name: Update certificate for validation
  command: update-ca-trust extract
  tags:
  - registry


- name: Test registry access
  uri:
    user: admin
    password: admin
    method: GET
    url: "https://{{ LOCAL_REGISTRY }}/v2/_catalog"
    validate_certs: no
  register: result
  tags:
  - registry


- name: Print test result if OK
  debug:
    msg: "Registry status for URL {{ result.url }} is OK!"
  when: result.status|int == 200
  tags:
  - registry



