---
# handlers file for registry

- name: Restart the firewalld service
  service:
    state: restarted
    daemon_reload: yes
    name: firewalld

- name: Restart the registry systemd service
  service:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: registry
