- name: Search for any existing s3bench pod
  shell: | 
    podman pod ps  
  register: containers_exist
  tags:
  - start_s3bench 

- name: Create A S3bench Pod If Not Exists
  shell: |
    podman pod create --name s3bench \
    -p 9200:9200 -p 9300:9300 -p 5601:5601
  when: containers_exist.stdout_lines | select('search', 's3bench') | list | length == 0
  tags:
  - start_s3bench

- name: Search for any existing s3bench instance  
  shell: | 
    podman ps -a  
  register: containers_exist
  tags:
  - start_s3bench

- name: Clean exsiting s3bench
  shell: | 
    podman rm -f s3bench{{ item }}
  with_sequence: start=0 end={{ containers_exist.stdout_lines | select('search', 's3bench') | list | length  - 1 if containers_exist.stdout_lines | select('search', 's3bench') | list | length > 0 else 0}}
  when: containers_exist.stdout_lines | select('search', 's3bench') | list | length | int != 0 
  tags:
  - start_s3bench

- name: Start s3bench container using Podman
  shell: |
    podman run --pod s3bench --name s3bench{{ item }} \
     -d {{ s3bench_image }} \
     --endpoint-url {{ endpoint_url }} \
     --access-key {{ access_key }} \
     --secret-key {{ secret_key }} \
     --bucket-name {{ bucket_name }} \
     --object-size {{ object_size }} \
     --elastic-url {{ elastic_url }} \
     --num-objects {{ num_objects }} \
     --workload {{ workload }} \
  tags:
  - start_s3bench
  with_sequence: start=0 end={{ s3bench_instances  - 1 }}  

